{% set version = "0.5.6" %}

package:
  name: openapi-spec-validator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-spec-validator/openapi_spec_validator-{{ version }}.tar.gz
  sha256: 1189d0618ae0678ccf6c883cc1266d381454eece6f21fcf330cc7caea5fc25eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - openapi-spec-validator = openapi_spec_validator.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0
    - python >=3.7

  run:
    # keep in sync with the poetry-generated setup.py
    - importlib_resources >=5.8.0,<6.0.0
    - jsonschema >=4.0.0,<5.0.0
    - jsonschema-spec >=0.1.1,<0.2.0
    - lazy-object-proxy >=1.7.1,<2.0.0
    - openapi-schema-validator >=0.4.2,<0.5
    - python >=3.7
    - pyyaml >=5.1

test:
  requires:
    - pip
  imports:
    - openapi_spec_validator
  commands:
    - pip check
    - openapi-spec-validator --help

about:
  home: https://github.com/p1c2u/openapi-spec-validator
  license: Apache-2.0
  summary: OpenAPI 2.0 (aka Swagger) and OpenAPI 3 spec validator
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/p1c2u/openapi-spec-validator
  description: |-
    OpenAPI Spec Validator is a Python library that validates OpenAPI Specs
    against the OpenAPI 2.0 (aka Swagger) and OpenAPI 3.0 specification. The
    validator aims to check for full compliance with the Specification.

extra:
  recipe-maintainers:
    - rvalieris
    - bollwyvl
