{% set version = "0.2.10" %}

package:
  name: openapi-spec-validator
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/p1c2u/openapi-spec-validator/archive/{{ version }}.tar.gz
  sha256: b8610d93533ae48f9d8d9534a2bcdb05787f58c7d093eb3acf2ecb557dbde35d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - openapi-spec-validator = openapi_spec_validator.__main__:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - jsonschema
    - six
    - setuptools
    - pyyaml
    - pathlib2

test:
  imports:
    - openapi_spec_validator

about:
  home: https://github.com/p1c2u/openapi-spec-validator
  license: Apache-2.0
  summary: OpenAPI Spec validator
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/p1c2u/openapi-spec-validator

extra:
  recipe-maintainers:
    - rvalieris
